# Generated by Django 5.1.6 on 2025-02-25 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('desc', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('comid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('processor', models.CharField(default='', max_length=200)),
                ('graphic', models.CharField(default='', max_length=200)),
                ('display', models.CharField(default='', max_length=200)),
                ('ram', models.CharField(default='', max_length=200)),
                ('Storage', models.CharField(default='', max_length=200)),
                ('OS', models.CharField(default='', max_length=200)),
                ('battery', models.CharField(default='', max_length=200)),
                ('warranty', models.CharField(default='', max_length=200)),
                ('weight', models.CharField(default='', max_length=200)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(default=None, upload_to='static/images/Computer')),
                ('net', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('storageid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('model', models.CharField(default='', max_length=200)),
                ('brand', models.CharField(default='', max_length=200)),
                ('RPM', models.CharField(default='', max_length=200)),
                ('Form_Factor', models.CharField(default='', max_length=200)),
                ('Random_Write', models.CharField(default='', max_length=200)),
                ('Random_Read', models.CharField(default='', max_length=200)),
                ('Sequential_Write', models.CharField(default='', max_length=200)),
                ('Sequential_Read', models.CharField(default='', max_length=200)),
                ('interface', models.CharField(default='', max_length=200)),
                ('technology', models.CharField(default='', max_length=200)),
                ('size_ssd', models.CharField(default='', max_length=200)),
                ('storage', models.CharField(default='', max_length=200)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(default=None, upload_to='static/images/Storage')),
                ('net', models.IntegerField(default=0)),
                ('warranty', models.CharField(default='', max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itApp.category')),
            ],
        ),
    ]
