# Generated by Django 5.1.6 on 2025-02-25 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('accid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('brand', models.CharField(default='', max_length=200)),
                ('model', models.CharField(default='', max_length=200)),
                ('color', models.CharField(default='', max_length=200)),
                ('keyswitch', models.CharField(default='', max_length=200)),
                ('keypresslifetime', models.CharField(default='', max_length=200)),
                ('numberkey', models.CharField(default='', max_length=200)),
                ('mediakey', models.CharField(default='', max_length=200)),
                ('interface', models.CharField(default='', max_length=200)),
                ('weight', models.CharField(default='', max_length=200)),
                ('price', models.FloatField(default=0.0)),
                ('size', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(default=None, upload_to='static/images/Accessories')),
                ('net', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itApp.category')),
            ],
        ),
    ]
