# Generated by Django 5.1.6 on 2025-02-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itApp', '0002_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
