# Generated by Django 5.1.6 on 2025-02-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itApp', '0002_accessories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network_Device',
            fields=[
                ('ntid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('brand', models.CharField(default='', max_length=200)),
                ('model', models.CharField(default='', max_length=200)),
                ('system_management', models.CharField(default='', max_length=200)),
                ('power_supply', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='accessories',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='computer',
            name='brand',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='computer',
            name='model',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='computer',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
