# Generated by Django 5.1.6 on 2025-02-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itApp', '0003_accessories_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='brand',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='computer',
            name='model',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='computer',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
