# Generated by Django 5.1.6 on 2025-02-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itApp', '0003_network_device_accessories_name_computer_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network_device',
            name='harddisk',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='network_device',
            name='memory',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='network_device',
            name='optical_drive',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='network_device',
            name='processor',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='network_device',
            name='processor_speed',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='network_device',
            name='raid_controller',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='network_device',
            name='warranty',
            field=models.IntegerField(default=0),
        ),
    ]
