# Generated by Django 5.1.6 on 2025-02-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itApp', '0004_network_device_harddisk_network_device_memory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='warranty',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='network_device',
            name='warranty',
            field=models.CharField(default='', max_length=200),
        ),
    ]
