# Generated by Django 5.1.6 on 2025-02-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itApp', '0004_computer_brand_computer_model_computer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='size_ssd',
            new_name='size',
        ),
        migrations.AddField(
            model_name='accessories',
            name='warranty',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='computer',
            name='warranty',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='storage',
            name='warranty',
            field=models.CharField(default='', max_length=3),
        ),
    ]
