# Generated by Django 5.1.6 on 2025-02-26 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itApp', '0005_accessories_warranty_alter_network_device_warranty'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('ntid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('brand', models.CharField(default='', max_length=200)),
                ('model', models.CharField(default='', max_length=200)),
                ('system_management', models.CharField(default='', max_length=200)),
                ('power_supply', models.CharField(default='', max_length=200)),
                ('optical_drive', models.CharField(default='', max_length=200)),
                ('raid_controller', models.CharField(default='', max_length=200)),
                ('harddisk', models.CharField(default='', max_length=200)),
                ('memory', models.CharField(default='', max_length=200)),
                ('processor_speed', models.CharField(default='', max_length=200)),
                ('processor', models.CharField(default='', max_length=200)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(default=None, upload_to='static/images/Storage')),
                ('net', models.IntegerField(default=0)),
                ('warranty', models.CharField(default='', max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itApp.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Network_Device',
        ),
    ]
