# Generated by Django 5.1.6 on 2025-02-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itApp', '0006_networkdevice_delete_network_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='image',
            field=models.ImageField(default=None, upload_to='static/images/NetworkDevice'),
        ),
    ]
