# Generated by Django 5.1.6 on 2025-02-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itApp', '0007_networkdevice_name_alter_networkdevice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='weight',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='storage',
            name='weight',
            field=models.CharField(default='', max_length=200),
        ),
    ]
