# Generated by Django 5.1.6 on 2025-02-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itApp', '0008_networkdevice_weight_storage_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='warranty',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='computer',
            name='warranty',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='warranty',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='storage',
            name='warranty',
            field=models.CharField(default='', max_length=10),
        ),
    ]
